Module Glossary_Strings
    'First Batch of Glossary Keywords
    Public Const String_Tool As String = "Keywords:-" & Chr(13) & "Tool, IDE, Code:Blocks, Integrated Development Environment, C Software, Compiler" & Chr(13) & "" & Chr(13) & "Introduction:-" & Chr(13) & "When making softwares using C Language a software called IDE(Integrated Development Environment) is generally used. It is the most common type of C software used. It is actually a collection of various softwares which are needed to properly convert a C code into an executable program." & Chr(13) & "" & Chr(13) & "Code:Blocks, the software that you are using is also an IDE. It is a free software and there are various versions for different Operating Systems like Windows, Linux, Mac." & Chr(13) & "" & Chr(13) & "This is not the only IDE present. There are many different IDEs. Some of them are free but there are many for which you have to pay money to use them." & Chr(13) & "" & Chr(13) & "There are many parts of an IDE. " & Chr(13) & "The two main parts that we usually deal with are the text editor and the compiler. The text editor is the part in which you type the code. Notepad is a simple example of a text editor. The other one - ""compiler"" is a type of software that you will mostly see when doing programming. It is a software that converts the code written in C language into instructions for the computer in the computer's ""machine language""." & Chr(13) & "" & Chr(13) & "When we press F9 in codeblocks we are actually starting the compile process. Compiler runs, converts C language into machine language and then we get our program."
    Public Const String_Open_Source As String = ""
    Public Const String_Glossarys As String = "Keywords:-" & Chr(13) & "Glossary, Keywords" & Chr(13) & "" & Chr(13) & "Meaning:-" & Chr(13) & "Keywords are those words that are seen mostly in a particular field. For example you will come across the word IDE most of the times when you are programming. So, IDE is a keyword related to programming" & Chr(13) & "" & Chr(13) & "Glossary means a list of terms in a particular field. A glossary is generally alphabetically arranged. For example this software has two glossaries:-" & Chr(13) & "1. Glossary of Keywords" & Chr(13) & "	It contains an alphabetical list of keywords related to general programming, C language and the software used for making C software. Some other keywords are also present in it." & Chr(13) & "2. Glossary of Libraries And Functions" & Chr(13) & "	It contains an alphabetical list of libraries and functions used in C lnaguage."
    Public Const String_Libraries As String = ""
    Public Const String_Tooltip As String = "Keywords:-" & Chr(13) & "Tooltip" & Chr(13) & "" & Chr(13) & "Where is this thing?" & Chr(13) & "When you start CodeBlocks you must have seen a windows that opens everytime. It has the heading 'ToolTip'. " & Chr(13) & "If it does not start when you start CodeBlocks then you can start it by going to Help Menu->Tips and then Tick the box ""Show Tips at Startup""." & Chr(13) & "" & Chr(13) & "So what is this tooltip?" & Chr(13) & "Tooltip is an a group of advices that the software shows you everytime. These tips contain information about how software works, about the shortcuts that you can use. In short tooltips display things that can make it easier for you to use the software."
    Public Const String_Code_Blocks_Shortcuts As String = "Keywords:-" & Chr(13) & "Code:Blocks Shortcuts" & Chr(13) & "" & Chr(13) & "1. Ctrl + Shift + N" & Chr(13) & "It can be used to create a new empty file" & Chr(13) & "" & Chr(13) & "2. Ctrl + D" & Chr(13) & "A. If used without selecting anything then the text of current line gets copied and pasted as-it-is in the next line" & Chr(13) & "B. If used after selecting some text then the selected text is copied and pasted where the selection ends" & Chr(13) & "" & Chr(13) & "3. Hold Ctrl and press Tab" & Chr(13) & "Is used to shift quickly between different files inside Code:blocks when more than one Source Codes are open." & Chr(13) & "" & Chr(13) & "4. F9" & Chr(13) & "Build And Run. Press this and if your Source Code has no syntax errors then your program will run"
    Public Const String_Programming As String = "Keywords:-" & Chr(13) & "Programming" & Chr(13) & "" & Chr(13) & "About:-" & Chr(13) & "Writing C Code is programming. " & Chr(13) & "Writing Codes in any computer language is programming." & Chr(13) & "" & Chr(13) & "Have you seen the apps on facebbok or the apps in android market?" & Chr(13) & "They are also made by programming. They were made by writing codes."
    Public Const String_C_Language As String = "Keywords:-" & Chr(13) & "C Language, Use of C Language" & Chr(13) & "" & Chr(13) & "About:-" & Chr(13) & "C Language is a general purpose programming language. It is widely used. Its main application areas include Operating System implementation and Embedded Systems. One of the main reasons of C language's popularity is its high-speed."
    Public Const String_Code As String = "Keywords:-" & Chr(13) & "Code, C Code, Source Code" & Chr(13) & "" & Chr(13) & "Introduction:-" & Chr(13) & "To make a software we need to write something in some computer language. That ""something"" which is written is called the code of the software or the Source Code." & Chr(13) & "" & Chr(13) & "While making C softwares you write codes in C Language. That is the ""C Code"" which will be used to make your program." & Chr(13) & "" & Chr(13) & "The following is an example of a source code." & Chr(13) & "/*-----------------------------------------" & Chr(13) & "#include<stdio.h>" & Chr(13) & "" & Chr(13) & "void main()" & Chr(13) & "{" & Chr(13) & "	printf(""AsD"");" & Chr(13) & "}" & Chr(13) & "------------------------------------------*/"
    Public Const String_Escape_Identifiers As String = "Keywords:-" & Chr(13) & "Escape Identifiers, New Line, Line Break, Tab Feed" & Chr(13) & "" & Chr(13) & "About:-" & Chr(13) & "When displaying something on the screen we have to use a function. The most common example is printf function. Inside such function there is a string of characters starting and ending with a quote(""). Whatever we wish to display can be written between the quotes. " & Chr(13) & "But if want something else to happen. Something like going into the next line or introducing a tab we have to use some special characters. These special characters are called escape identifiers. They start with backslash(\). Two examples are \n and \t." & Chr(13) & "" & Chr(13) & "\n (New Line or Line Break)" & Chr(13) & "When we write this inside a printing statement the characters appearing after this are dislayed in the next line." & Chr(13) & "" & Chr(13) & "\t(Tab Feed)" & Chr(13) & "When we write this inside a printing statement the characters appearing after this are dislayed after a tab."
    Public Const String_Comments As String = "Keywords:-" & Chr(13) & "Comments" & Chr(13) & "" & Chr(13) & "Comments are used in programming languages for many things:-" & Chr(13) & "1. Make the Code easy to read. " & Chr(13) & "This is done by entering comments with every different logic implemented. Simply writing what a particular piece of code does makes the code easier to read." & Chr(13) & "2. Commenting Out part of the Code. " & Chr(13) & "Any Code placed inside comments does not affect the program. It becomes inactive. So it is possible to let some code remain in your Source Code which is actually inactive. This is called commenting out part of the code. The part of the code inside the comments is OUT OF WORKING."

    'Second Batch of Glossary Keywords

End Module
