Module Menu_Strings

    Public Const String_Start As String = "		START	Lesson 00" & Chr(13) & "" & Chr(13) & "How to start using this Software?" & Chr(13) & "" & Chr(13) & "1. Click on Lesson 01 in the list of Lessons. " & Chr(13) & "2. Click on the button =>Lesson Selected<= " & Chr(13) & "" & Chr(13) & "    Some Steps are displayed in the List of Steps" & Chr(13) & "" & Chr(13) & "3. Click on Step 01 in the List of Steps" & Chr(13) & "" & Chr(13) & "   After following the instruction in 4th point the text displayed on this screen will change" & Chr(13) & "   Just read the instructions given there and follow them" & Chr(13) & "" & Chr(13) & "4. Click on the button =>Step Selected<="
    Public Const String_About As String = "	ABOUT THE AUTHOR AND THIS PROJECT" & Chr(13) & "" & Chr(13) & "Developer" & Chr(13) & "		Aseem Bansal" & Chr(13) & "" & Chr(13) & "Project Started on" & Chr(13) & "		24th August 2012" & Chr(13) & "" & Chr(13) & Form1.String_Version & " released  on =>" & Chr(13) & "		" & Form1.String_Version_Release
    Public Const String_Help As String = "		CONTACT INFORMATION" & Chr(13) & "" & Chr(13) & "This is still a work in progress." & Chr(13) & "There may be problems even if I make sure to make it error-free." & Chr(13) & "There may be some functions that are difficult to use." & Chr(13) & "" & Chr(13) & "If you want to tell about any problem, any feature that is difficult to use or give any suggestion then you can contact me at the e-mail address given below." & Chr(13) & "" & Chr(13) & "CONTACT:-" & Chr(13) & "aseembansal@ymail.com" & Chr(13) & "" & Chr(13) & "Please write [C Programming Made A Game] in the title of the e-mail"
    Public Const String_Technical As String = "			Technical Details" & Chr(13) & "" & Chr(13) & "Tool on which the Codes have been tested" & Chr(13) & "		Code:Blocks (An Open Source C/C++ IDE) from http://www.codeblocks.org/downloads/26#windows "
    Public Const String_Update As String = "		UPDATES" & Chr(13) & "" & Chr(13) & "https://programmingmadeagame.wordpress.com/download-links/" & Chr(13) & "" & Chr(13) & "The above link is the website at which the latest version of this software will always be posted at the top" & Chr(13) & "" & Chr(13) & "If you have downloaded a new version of this software then you do not need to uninstall this version. The Setup of the new version will automatically update the software."
    Public Const String_Why_Use_This_Software As String = "You may be thinking ""Why should I use this Software?""" & Chr(13) & "" & Chr(13) & "   The answer is" & Chr(13) & "       1. Because it can teach you to make softwares easily" & Chr(13) & "       2. Because it is simple to learn by using this software" & Chr(13) & "       3. Because this software will be updated regularly and you will get new content frequently"
    Public Const String_Glossary As String = "Glossary is a support resource under development. " & Chr(13) & "" & Chr(13) & "It contains gloassary of " & Chr(13) & "	Keywords" & Chr(13) & "	Libraries And Functions" & Chr(13) & "					" & Chr(13) & "Glossary of Keywords" & Chr(13) & "		It contains detials about various keywords used in this software and which we see while making softwares in C. Things whose definitions you will find in books will be explained here in simple words." & Chr(13) & "		" & Chr(13) & "Glossary of Libraries and Functions" & Chr(13) & "		It contains details about various Libraries that have to be used when making softwares. Also detials regarding the functions that are defined in the libraries are provided."

End Module
